# Generated by Django 5.1.2 on 2024-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('quantity', models.IntegerField(max_length=100)),
                ('supplier', models.CharField(max_length=1000)),
            ],
        ),
    ]
